### ISSUE TITLE
Define an expression MIR

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/moore#104]
Expressions in SystemVerilog are very rich and imply a lot of implicit casting, extension, and truncation. It is likely beneficial to specify a mid-level intermediate representation (MIR) for expressions which reduces this to a small set of well-defined and fully typed expressions.

The associated query would go from an expression's HIR (`hir::Expr`) and corresponding type information after type checking and produce an MIR expression (`mir::Expr`). The latter has every expression fully typed and all names, operators, functions, etc. are fully known and resolved. All casts, extensions, and truncations are converted to explicit expression nodes.

The goal is to make processing of expressions easier by lowering them to a well-defined level. For example, to lower a binary operator to MIR, its operands would have their MIR determined, then optional cast nodes would be generated to match the operator's result type, then a node for the operator itself would be generated.

Similarly, lvalues would also get a proper MIR representation and represent the subset of expressions which can actually be assigned to.

### Todo
- [x] Define nodes
- [x] Add interning mechanism
- [x] ~Implement visitor pattern~
- [x] ~Implement MIR pretty printing~
- [x] Add MIR for expression lvalues
- [x] Add codegen for lvalues

**Comment by fabianschuiki** [comment]
MIR-based rvalue code generation is now the default since fa6fd1668.

**Comment by fabianschuiki** [comment]
MIR-based lvalue code generation is now the default since 680ace2.
