### ISSUE TITLE
Improve type checking

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/moore#111]
Currently type checking is performed in one go. This yields incorrect results and does not capture all the crazy intricacies of SystemVerilog. Expressions can have a self-determined type, may be within an assignment-like context, operators have an internal operation type, and thus expressions derive a final type. This requires splitting things up into separate queries:

- **Type context:** Visit parent node and ask for type context. Parent determines based on all the crazy svlog rules. See 11.8. `(NodeId, ParamEnv) -> Option<Type>`
- **Self-determined type:** This is pretty much what already exists. But can fail, e.g. for `'{...}`. `(NodeId, ParamEnv) -> Option<Type>`
- **Operation type:** Determines what type an operator has. This is useful for comparisons, where the internal type is not equal to the operator's return type. `(NodeId, ParamEnv) -> Type`
- **Final type:** Consult the type context and self-determined type where needed. Can usually fall back to one of the above queries. `(NodeId, ParamEnv) -> Type`

## Todo

- [x] Add query for type context
- [x] Add query for self-determined type
- [x] Add query for operation type
- [x] Update query that performs type computation

**Comment by fabianschuiki** [comment]
The type context must be able to communicate implicit bool conversion, which are different than "forcing" the result to be `bit` or `logic`. The bool conversion checks for a non-zero value, while the implicit cast to `bit` or `logic` simply truncates upper bits.

Maybe we need something like:
```
enum TypeCtx<'a> {
    None,
    Type(Type<'a>),
    Bool,
}
```

**Comment by fabianschuiki** [comment]
Pretty much implemented as of 4bfccf6. What's missing now is the MIR making use of the finer-grained type queries to determine the operation type of binary operators.
