### ISSUE TITLE
Implement `inside` expression

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/moore#112]
Implement lowering to HIR and MIR of `inside` expressions. Code generation changes should not be needed since the expression should be fully representable in the MIR. A possible example could be:
```
inst_data_i[14:12] inside {[3'b000:3'b100], 3'b111}
```
In the MIR, the different elements of the set `{...}` produce a large OR reduction. Each element is either an equality comparison with the LHS (if it's a single value), or an AND node of inequality checks between the LHS and the lower and upper bound (if it's a range). Pure syntactic sugar.

### Todo
- [x] Fix parser precedence for `inside`; seems to be wrong
- [x] Lower to HIR
- [x] Lower to MIR

**Comment by fabianschuiki** [comment]
Implemented in 511971ade.
