### ISSUE TITLE
Deprecate the `BitScalar` type

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/moore#116]
Get rid of the `BitScalar` type, which is used to represent `logic`, in contrast to `logic [1:0]` which would be a `BitVector` type. However this introduces a lot of irregularity and in general it seems to be preferred to treat all logics plus an optional first dimension as `BitVector`.

### Todo
- [ ] Mark the `BitScalar` variant as `#[deprecated]`.
- [ ] Follow the warnings and phase out the variant.
- [ ] Remove the variant and delete all the now-breaking match arms.
