### ISSUE TITLE
Add support for ANSI and non-ANSI port lists

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/moore#128]
We currently only really support ANSI port lists. However a lot of Verilog code uses non-ANSI port lists, which should be supported properly. Add proper support for the two:
```
// Non-ANSI
module foo (a, b, z);
    input a, b;
    output z;
    z <= a & b;
endmodule

// ANSI
module bar (input a, input b, output z);
    z <= a & b;
endmodule
```

Fixes #105 once implemented.

## Todo
- [x] Add test cases from the standard.
- [x] Fix issues in parsing ANSI port lists (easier case since ports are self-contained).
- [x] Add a query on the AST which determines the port layout of a module.
- [x] In the module body, filter out port and wire declarations which are part of the port layout. Warn about port declarations in generate statements.
- [x] Switch typeck to use the new HIR ports.
- [x] Switch name resolution to use the new HIR ports.
- [x] Change codegen to use the internal ports for module code generation.
- [x] Change codegen to use the external ports for module connection, mapping things to the internal ports.
- [x] Add support for explicit ANSI ports (`.P1(foo)`).
- [x] ~~Add support for select in port expressions (`.P1(foo[7:0])`)~~ (in #134)
- [x] ~~Add support for concatenations in port expressions (`.P1({x,y})`)~~ (in #134)
