### ISSUE TITLE
Implement connecting non-trivial port expressions

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/moore#134]
Currently only simple port expressions (without selects) can be connected to in instantiations. Everything else causes an error (hopefully). Fix this by allowing all port expressions to be connected to, which requires the connected signals to be destructured to map to the different expression parts.

## Todo
- [ ] Implement typeck on external ports
- [ ] Add support for select in port expressions (`.P1(foo[7:0])`)
- [ ] Add support for concatenations in port expressions (`.P1({x,y})`)
