### ISSUE TITLE
Parameters erroneously use types of bound value

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/moore#141]
When performing constant evaluation and type checking of parameters, the parameter evaluates to the type of the bound value *regardless of the parameter's type*. The standard specifies that the parameter type takes precedence in this case. For example:
```
module foo;
    localparam bit [7:0] X = 42'd123;
    bit [9:0] x = X;
endmodule
```
In this case `x` is emitted as `i42`, rather than `i10`. This means that (1) the parameter value is not cast to the parameter type properly, and (2) the type of signal `x` is not considered in code generation.

Fixing this is likely going to entail migrating constant value computation to the MIR, where casts have been properly resolved. Otherwise the two paths would become highly redundant.

### Todo
- [x] Fix typeck to use parameter type rather than bound value when appropriate
- [x] Use MIR for constant evaluation (#149)
- [ ] Fix implicit cast not being inferred in `x = X`, since type context for `X` is never consulted. (Related to #151)
