### ISSUE TITLE
Implement interfaces

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/moore#145]
Implement SystemVerilog interfaces. Parsing is mostly there, but they need to be lowered to HIR, typeck'd, and codegen'd. The tricky part will be parametric interfaces: the actual interface passed through an interface port implicitly parametrizes the module. During codegen, interface ports can either be fully unrolled, or wrapped in two structs (input and output).

## Todo
- [x] Extend `port_list` module to cover interfaces
- [x] Lower interfaces to HIR
- [x] Extend `inst_details` to also support module targets
- [x] Support interfaces in module bodies
- [x] Allow driving/probing of interface signals
    - [x] In concurrent assignments
    - [x] In processes
- [x] Implement interfaces in module port lists
- [x] Remove special treatment in HIR lowering (`LocalIntfSignal`)
- [x] Implement modports
    - [x] Add modport type
    - [x] Generate modport type during typeck
    - [x] Properly parse modport contents
    - [x] Consider port directions in modport during codegen
- [x] Implement passing interfaces to module instances
- [x] Allow interfaces to implicitly cast to a modport in typeck
- [x] Support unpacked arrays of interfaces
- [x] Implement interface parametrization
    - [x] In instantiations
    - [x] In ports
    - [x] When accessed in a process
- [x] Consider interfaces as part of a module's parametrization
- [x] Honor port assignments in interface instantiation
