### ISSUE TITLE
Overhaul type system

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/moore#146]
The type system is rather ad-hoc at the moment. Especially, types are treated as minimal "nuggets" of information: e.g. arrays wrap an inner type. But SystemVerilog uses a more rigid and clunky scheme, where a type has some core type (`bit`, `logic`, `void`, a struct, a name alias, etc.) plus separate sign, packed, and unpacked dimensions. This should be reflected as such in the type system, because many operations/transformations rely on tweaking parts of this information (e.g. going from `wire signed [7:0]` to `wire logic signed [7:0]`).

What an overhauled type system must support:
- Dubbed types (e.g. `int` instead of `bit [31:0]`)
- Distinguish between scalar and single-bit vector (`bit` vs. `bit [0:0]`)
- Track packed and unpacked dimensions separately
- Sign and size casts
- Casting to an SBVT (simple bit vector type)
- Typedefs and named types as core type:
  ```
  typedef logic [3:6] foo_t [3];
  foo_t bar [42];
  ```
- Resolve names and indirections in the core type, e.g. from above:
  ```
  logic [3:6] bar [3][42];
  ```

## Todo
- [x] Design new types in `ty` to better represent SystemVerilog types
- [x] Introduce `TypeContext` trait that handles type interning and operations
- [x] Use lazy static for fundamental types to maintain rust 1.38 compatibility
- [x] Resolve `Named` and `Ref` to the underlying type
- [x] Add function to check if two types are identical
- [x] Add explicit simple bit vector type in `ty`
- [x] Add function to convert between regular types and SBVTs
- [x] Implement all the size, sign, domain, and SBVT casting
- [x] Switch MIR to these new types
- [x] Fix failing tests due to MIR switch
- [x] Switch constant values to these new types
- [x] Implement code generation for the new types
- [x] Switch expr typing queries to these new types
- [x] Change `signing` to `sign` in the new types
- [x] Create replacement queries for typeck that yield these new types
- [x] Switch all type queries to the new query system
- [x] Deprecate and remove old types
- [x] Document expression type computation in `typeck` module

**Comment by fabianschuiki** [comment]
Finished in f8d494dbf.
