### ISSUE TITLE
Builtin $bits function cannot be called on type

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/moore#158]
SystemVerilog has this beautiful feature where `$bits(x)` accepts an expression or a type for `x`. This is pretty annoying, since quite a few types actaully look like expressions, and vice versa. Currently, using a type in `$bits` does not work:
```
module foo;
    parameter int a = 42;
    parameter type b = logic [41:0];
    int x0 = $bits(42);
    int x1 = $bits(logic [41:0]);
    int x2 = $bits(a);
    int x3 = $bits(b);
endmodule
```
This for one complains about not being able to parse `x1 = ...` due to the type used in the arguments to `$bits`. If that is commented out for now, the compiler complains about not being able to compute a type for `parameter type b`. This happens because the `b` in `$bits(b)` is treated as an expression, and the compiler calls `type_of(b)` at some point, which tries to figure out the type of `b`. However getting the type of a type parameter is nonsensical; rather, the type parameter can be mapped/evaluated to a type via the `map_to_type(b)` query.

This needs a means to resolve type/expression ambiguities, which is possible as soon as names have been resolved. There is a similar situation in the handling of casts:
https://github.com/fabianschuiki/moore/blob/master/src/svlog/hir/lowering.rs#L2091-L2119

However this also needs changes to the parser in order to accept `TypeOrExpr` on certain builtin calls.

## Todo
- [ ] Implement `$bits(logic [41:0])` in the parser
- [ ] Disambiguate `TypeOrExpr` as we lower the expression to HIR
- [ ] Properly implement both variants of `$bits`
