### ISSUE TITLE
Determine casts and final types during typeck

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/moore#162]
Typeck is currently pretty dumb, in that it just looks at the self-determined type of an expression if possible, and otherwise checks if something can be inferred from the type context. This results in `type_of` returning a type that is highly biased to the self-determined type of an expression.

On the other hand there is the implicit cast generation during the MIR lowering. This basically looks at the `type_of` a lowered argument MIR, then inserts implicit casts to match some vague `type_of` or `operation_type` of the current expression.

What should actually happen is that **implicit casts should be determined during typeck**. The `type_of` an expression should then always return the final type after implicit casts, which must *always match* its type context. Failure to match would be a type error, since after implicit casts there's really nothing left in the pipeline which would change types. So actually expressions *should not* have a `type_of` query, but rather a `cast_type`, which returns not only a type, but the entire cast chain needed to translate the type. This includes things like packing/unpacking simple bit vector types -- pretty much what is already implement in the MIR.

Typeck then becomes pretty simple: Everything just considers the `cast_type`, and checks against any constraints a node might have. E.g., operators get the cast type of their operands, which *must match* the operation type.

MIR lowering would then not need to guess casts everywhere. Rather, operator arguments would simply be mapped to MIR, asserted to match the operation type, and a new operator node would be created. As a post-processing step after lowering every MIR node, the `cast_type` would be consulted and the resulting chain of casts would be emitted as additional wrapper MIR nodes.

## Todo
- [x] Add `cast_type` query on expressions (inherit behaviour from MIR lowering)
- [x] ~~Have arithmetic operators emit a *"needs-SBVT"* type context~~
- [x] ~~Have indexing operators emit a *"needs-indexable"* type context~~
- [x] Consult `cast_type` during MIR lowering and emit casts around each rvalue
- [x] Convert type diagnostics in MIR to `assert!(...)`
- [x] MIR lowering:Replace all `lower_expr_and_cast` with `mir_rvalue`
- [x] MIR lowering: Deprecate and delete `implicit_cast_to_bool`
- [x] MIR lowering: Deprecate and delete `cast_to_bool`
- [x] MIR lowering: Deprecate and delete `cast_to_type`
- [x] Fix assertion failure on `!b` operator (see `test/svlog/typeck/cast.sv:12`)
- [x] Land #165 to fix introduced instance lowering issues
- [x] Deprecate `type_of` on expressions (or at least forward to `cast_type`)
