### ISSUE TITLE
Create query for instance param env and port mapping

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/moore#165]
Add the following compiler queries:
- [x] One which for an instantiation returns the corresponding parameter environment
- [x] One which for an instantiation returns the parameter and port mapping

Then update typeck to use the parameter and port mapping to impose a type context on the expression assigned to a parameter or port.

## Todo
- [x] Add `inst_details` query
- [x] Add `inst_target_details` query
- [x] Add inst params/ports to HIR visitor
- [x] Impose port as type context
- [x] Impose parameter as type context
- [x] Implement `typeck` on `ExtPort`
