### ISSUE TITLE
Infer type context and cast for array/struct pattern fields

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/moore#166]
Currently the casting of expressions assigned to fields in array/struct patterns occurs during MIR lowering. Since we have now introduced the `cast_type` query, these things should happen during `typeck`, and the MIR lowering should simply be able to assemble the patterns.

## Todo
- [x] Land pattern query (#173)
- [x] Migrate casting logic in `lower_array_pattern` to typeck
- [x] Migrate casting logic in `lower_struct_pattern` to typeck
- [x] Update `lower_array_pattern` and `lower_struct_pattern` to use the `cast_type` query for fields
- [x] Add corresponding tests for pattern on LHS and RHS
