### ISSUE TITLE
Implement function calls

### ISSUE THREAD

**Issue by tampler** [fabianschuiki/moore#168]
Tracking issue for the implementation of function calls.

## Todo
- [x] Fix parser issue for `test/svlog/funcs/std_example.sv`
- [x] Add ambiguity resolution for subroutine port declarations, e.g. `test/svlog/funcs/std_example.sv`
- [x] Add query to distill ANSI/non-ANSI function arguments into a canonicalized form
- [x] Fix parsing of function calls as statements (#213)
- [x] Resolve simple function calls (free and in package scopes)
- [x] Add query to pair up function call arguments with function definition arguments
- [x] Add verbosity option to show function resolution and type checking (visitor over AST)
- [x] Impose type context on call arguments based on definition
- [x] Emit function definitions as LLHD `func`s
- [x] Lower calls to MIR
- [x] Emit calls as LLHD `call`s
- [x] Fix tests broken by tighter argument type computation

---
Hello Fabian

Started to learn about this project. This work is awesome! Thanks for contributing a lot of effort and building this!

I tried to compile an example from your paper with `moore` and got a bug. Just to let you know about this issue. Here's the [file](https://drive.google.com/open?id=1Iv2Jptlt0NJTm9-qGzJw2zH5nqzQ1pn)
```bash
bku@lap:~/work/hw/llhd/moore/0$ moore -O4 tb.sv -e acc_tb
compiler bug: lowering of call to expression not implemented
  --> tb.sv:13:3-8: 
   |   check(i, q);
```

**Comment by fabianschuiki** [comment]
Hi @tampler, thanks for the heads up. There are a few parts of the examples in the paper that moore does not yet fully support, but was in the paper for the sake of completeness (and show how things would map to LLHD). I'm working on getting this done though :+1:. Changing this into a tracking issue for function calls.

**Comment by tampler** [comment]
Sure take your time. I'll be keeping my eye on this project and your awesome work

**Comment by fabianschuiki** [comment]
Thanks! Any SystemVerilog code snippets that you find which are rejected by moore are very welcome here on the issue tracker :smiley: !
