### ISSUE TITLE
Name resolution blows the stack in large designs

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/moore#171]
Reasonably large designs can cause a stack overflow due to the way how `local_rib` in `resolver.rs` is designed: it escalates upwards by recursion, with the stack size required being `O(#statements)` in the imported packages and the current module. This should rather be `O(nesting depth)`.

This goes well with the parent/sibling/ID added to the AST as part of #130: Name resolution could then occur purely on the AST, and rather than long recursive call chains, it would build name resolution scopes (local and hierarchical) in a top-down fashion. This will also allow for disambiguation of AST ambiguities based on resolved names.

## Todo
- [x] Land #130.
- [x] Enumerate statements in blocks, to determine which names of the scope are visible.
- [x] Add a function to register a name in a scope (distinguish between local/hierarchical resolution)
- [x] Add a query to determine the resolution scope of a node: `scope(&ast::Node<T>) -> Scope`
- [x] ~~Add a verbosity option to visit the AST (#130) and emit the resolution scope details~~
- [x] Use the `scope` query to resolve names
- [x] Bring new queries to feature parity with old ones
  - Local rib:
    - [x] TypeParam
    - [x] ValueParam
    - [x] Module
    - [x] VarDecl
    - [x] NetDecl
    - [x] GenvarDecl
    - [x] Stmt
    - [x] Package
    - [x] Type
    - [x] Import
    - [x] SubroutineDecl
  - Hierarchical rib:
    - [x] Package
    - [x] Module
- [x] Make old resolution code use the new queries
- [x] ~~Deprecate and remove old queries~~ (Better wait for this to happen on its own)
