### ISSUE TITLE
Implement assignment expressions

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/moore#172]
Implement HIR lowering, typeck, and codegen of assignment expressions such as the following:
```
for (int i = 0; i < N; i += 1) begin
//                     ^^^^^^ this here
end
```

## Todo
- [x] Lower expression to HIR
- [x] Implement the various typeck queries
- [x] Implement lowering to MIR (`Assignment` rvalue)
