### ISSUE TITLE
Implement assigning to concatenations

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/moore#185]
Assigning to a concatenation of values is not yet supported in MIR lvalue lowering:
```
module foo;
    logic [7:0] a;
    logic [3:0] b;
    initial begin
        {a} = 8'd42;
        {a, b} = 12'd42;
        {a[1:0], b[1:0]} = 4'hA;
    end
endmodule
```
This will require adjusting lvalue code generation, which currently just returns a signal/pointer to assign. One option here is to take the array/struct destructuring in the lvalue and map them to corresponding slicing/field accesses on the rvalue side. This could be handled by adding a special `Assignment` node to the MIR, analogous to `Lvalue` and `Rvalue`, which encapsulate an assignment and performs this destructuring.

## Todo
- [x] Add `Assignment` MIR node
- [x] Implement simplification pass that lowers an assignment with complex lvalue to multiple assignments with simple lvalues
- [x] Use assignment node in code generation
