### ISSUE TITLE
Canonicalize param env before codegen

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/moore#187]
Codegen currently uses the `ParamEnv` to determine if two modules have the same parametrization. However, since most parameters are indirectly bound, i.e., they depend on outer parameters, these param envs look distinct in many cases, even though they will resolve to the exact same parametrization. To fix this, codegen should "canonicalize" the param envs, which would mean going through the param env data, converting each binding to a `Direct` one with the concrete value/type, and interning this as new param env. Then use this canonical param env for code generation.

## Todo
- [ ] Create a `canonical_param_type` and `canonical_param_value` query, which resolves *one* param
- [ ] Create a `canonical_param_env` query which creates a canonicalized param env
- [ ] Use the above in codegen before emitting a module
