### ISSUE TITLE
Assignment to bit select of struct as SBVT fails

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/moore#195]
Assigning to a bit select of a struct does not work. This should actually cause the struct to be cast to a simple bit vector type, such that the bit can be accessed. However `typeck` at the moment simply refuses to cast lvalues. This is bad, since lvalues should actually support limited forms of casts, including casting as SBVT.

The `id_queue` instance in `test/svlog/common_cells.sv` is a good example.

## Todo
- [x] Cast lvalue structs used as target for selects to SBVT
- [x] Include casts during MIR lvalue lowering (this might be tricky)
- [ ] Extend assignment simplification to support struct packing
- [ ] Extend assignment simplification to transpose SBVT casts onto the RHS of the assignment

**Comment by fabianschuiki** [comment]
#208 seems related.

**Comment by fabianschuiki** [comment]
The problem here is the fact that indexing into a struct causes the struct to be packed into an SBVT, which is then indexed. This translates to an lvalue along the lines of:
```
_0 = Lvalue Var(n23) : struct packed { logic [1:0] a; logic [2:0] b; logic [3:0] c; } [3:0]
_1 = Rvalue 0 : int
_2 = Lvalue _0[_1] : struct packed { logic [1:0] a; logic [2:0] b; logic [3:0] c; }
_3 = Lvalue _2.0 : logic [1:0]
_4 = Lvalue Transmute(_3) : logic [1:0]
_5 = Lvalue _2.1 : logic [2:0]
_6 = Lvalue Transmute(_5) : logic [2:0]
_7 = Lvalue _2.2 : logic [3:0]
_8 = Lvalue Transmute(_7) : logic [3:0]
_9 = Lvalue Concat(_4, _6, _8) : logic [8:0]
_10 = Rvalue 0 : int
_11 = Lvalue _9[_10] : logic
[...]
Assign _11 = [...] : logic
```
Which essentially is `{x.a, x.b, x.c}[0]` when translated back to SV. To make this work, the index operation must be simplified by limiting the concatenation to the subset that is actually being accessed. In this case trivially `x.c[0]`. For ranges, e.g. `{x.a, x.b, x.c}[7:1]`, this would require simplifying the concatenation to `{x.a[0:0], x.b, x.c[3:1]}`.
