### ISSUE TITLE
Implement array index operator

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/moore#75]
Implement array index operators:
```
module A;
	int x;
	int y;
	always @(x) y = x[16:4];
endmodule
```

Currently fails with:
```
compiler bug: lowering of expression not implemented
  --> /tmp/stuff.sv:4:18-25:
   | 
   |     always @(x) y = x[16:4];
   |                     ^^^^^^^ 
```

# Todo
- [x] Emit array types in assembly.
- [x] Implement array member access as rvalue.
- [x] Implement array member acccess as lvalue.
- [x] Use new llhd instructions once released.
- [x] Non-constant index/range accesses, aka muxers.

**Comment by fabianschuiki** [comment]
We need a way to emit instructions for multiplexers, i.e. array accesses that have a non-constant index. For example the following:
```
module A;
    int [15:0] a;
    int b;
    int c;
    always_comb c = a[b];
endmodule
```
There are a few different options as to how `a[b]` can be emitted.

### Using a rotation/shift instruction

We could introduce an additional llhd instruction that can rotate or shift an integer or array by a dynamic amount. This could be done as an extension to the existing `shl` and `shr` instructions. The access would then occur as:
```
%0 = prb [16 x i32]$ %a
%1 = prb i32$ %b
%2 = shr [16 x i32] %0, i32 %1
%3 = extract element [16 x i32] %2, i1 0
drv i32$ %c, %3
```

### Using `extract` extended to support dynamic bases

We could extend the `extract` instruction such that it allows for a dynamic offset value as well. It is not yet clear how we would define what value is returned if the offset value is out of bounds. The access would then occur as:
```
%0 = prb [16 x i32]$ %a
%1 = prb i32$ %b
%2 = extract element [16 x i32] %2, i32 %1
drv i32$ %c, %2
```

### Using a dedicated mux instruction

We could also define a separate `mux` instruction which has the necessary semantics to select among a set of signals based on a dynamic index. This only covers the case of single-element accesses though. Accessing a slice of elements would require additional semantics, since we would be selecting a subrange of elements.

**Comment by fabianschuiki** [comment]
Using an array as lvalue could be implemented using the `extract` instruction, as follows:
```
module A;
	int x;
	initial x[16:4] = 42;
endmodule
```
would be emitted as:
```
; in initial process
%0 = extract slice i32$ %x, 4, 13
drv i13$ %0, i13 42
```

**Comment by fabianschuiki** [comment]
Here goes another stab at variable indices (`a[i]`) and slices (`a[i+:8]` and `a[i-:8]`). Basically we leverage the shift instruction which will need to be extended slightly to also support shifting pointers and signals.

### Examples
Assume the following snippet of code to be in effect:
```
int i;
int a;
int [15:0] b;
```

#### Variable element index as rvalue
```
a[i]
b[i]
```
will generate
```
%a0 = shr i32 %a, i1 0, %i
%a1 = extract element i32 %a0, 0
; typeof(%a1) = i1
%b0 = shr [16 x i32] %b, i32 0, %i
%b1 = extract element [16 x i32] %b0, 0
; typeof(%b1) = i32
```

#### Variable slice index as rvalue
```
a[i+:8]
b[i+:8]
```
will generate
```
%a0 = shr i32 %a, i1 0, %i
%a1 = extract slice i32 %a0, 0, 8
; typeof(%a1) = i8
%b0 = shr [16 x i32] %b, i32 0, %i
%b1 = extract slice i32 %b0, 0, 8
; typeof(%b1) = [8 x i32]
```

#### Variable element index as lvalue
```
a[i] = 42;
b[i] = 42;
```
will generate
```
%dummy_a = sig i1
%a0 = shr i32$ %a, %dummy_a, %i
%a1 = extract element i32$ %a0, 0
drv i1$ %a1, i1 42
%dummy_b = sig i1
%b0 = shr [16 x i32]$ %b, %dummy_b, %i
%b1 = extract element [16 x i32]$ %b0, 0
drv i32$ %b1, i32 42
```

#### Variable slice index as lvalue
```
a[i+:8] = 42;
b[i+:8] = '{default: 42};
```
will generate
```
%dummy_a = sig i1
%a0 = shr i32$ %a, %dummy_a, %i
%a1 = extract slice i32$ %a0, 0, 8
drv i8$ %a1, i8 42
%dummy_b = sig i32
%b0 = shr [16 x i32]$ %b, %dummy_b, %i
%b1 = extract slice [16 x i32]$ %b0, 0, 8
drv [8 x i32]$ %b1, [8 x i32 42]
```

**Comment by fabianschuiki** [comment]
Implemented in dc4f87d15.
