### ISSUE TITLE
Implement struct types

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/moore#76]
Implement struct types:
```
module A;
    struct packed {
        logic a;
        int b;
    } x;
endmodule
```
Additional work will be required to map this to LLHD, and to implement accessing individual elements. Especially if the struct is a signal. It might be required to always fully copy the struct, modify the field, and then drive the signal with the copy for now.

# Todo
- [x] Emit struct types in assembly.
- [x] Implement struct member access as rvalue.
- [x] Implement struct member acccess as lvalue.
- [x] Use new llhd instructions once released.

**Comment by fabianschuiki** [comment]
Struct types are now properly emitted in LLHD. However accessing struct elements is still missing:
```
module A;
    struct {
        int a;
    } x;

    initial x.a = 15;
endmodule
```
This might get fairly complicated due to the way multiple drives can interact with each other. E.g. it is probably fine for an *unpacked* struct to have different drivers for different fields, but a *packed* struct is probably treated as one entity that cannot be driven independently.

**Comment by fabianschuiki** [comment]
Struct fields as lvalues could be implemented using the `extract` instruction. Given a struct signal, the instruction would resolve a field access to another signal which can be driven. This pushes the effort of subdividing a struct into independently drivable pieces into llhd.

### Example
```
// in a module
struct {
    int a;
    shortint b;
} x;

// in a process
x.a = 15;
```
would be emitted as:
```
%0 = extract element {i32, i16}$ %x, 0
drv i32$ %0, i32 15
```

**Comment by fabianschuiki** [comment]
This is done as of 6d9ed13.
